services:

  mcp:
    image: cadasto/openehr-assistant-mcp-dev:latest
    build:
      target: development
    tty: true
    volumes:
      - ./:/app
      - composer-cache:/data/.cache/composer

  caddy:
    ports:
      - "8343:8343"
      - "80:80"
      - "443:443"
      - "443:443/udp"

volumes:
  composer-cache:
